import type { LucideIcon } from "lucide-react";
import { Code2, Edit3, FileImage, FileSpreadsheet, FileText, FileType, Mic, QrCode, Sheet } from "lucide-react";

export type ToolCategory = "pdf" | "imagem" | "conversores" | "audio";

export type ToolDefinition = {
  slug: string;
  title: string;
  shortTitle: string;
  description: string;
  longDescription: string;
  href: string;
  status: "available" | "soon";
  category: ToolCategory;
  icon: LucideIcon;
  accent: "html" | "image" | "word" | "excel" | "pdf" | "edit" | "audio" | "qr";
  seoTitle: string;
  seoDescription: string;
};

export const tools: ToolDefinition[] = [
  {
    slug: "transcrever-audio-em-texto",
    title: "Transcrever áudio em texto",
    shortTitle: "Áudio para texto",
    description: "Transforme áudio ou vídeo curto em texto editável.",
    longDescription: "Envie MP3, WAV, M4A, OGG, WEBM ou MP4 e receba uma transcrição em TXT para copiar, revisar ou salvar.",
    href: "/transcrever-audio-em-texto",
    status: "available",
    category: "audio",
    icon: Mic,
    accent: "audio",
    seoTitle: "Transcrever áudio em texto online",
    seoDescription: "Transcreva áudio em texto online e baixe a transcrição em TXT sem instalar programas.",
  },
  {
    slug: "qr-code",
    title: "Gerador de QR Code",
    shortTitle: "QR Code",
    description: "Crie QR Code para links, textos, contatos e informacoes.",
    longDescription: "Digite um link ou texto e gere um QR Code em PNG, pronto para imprimir, compartilhar ou usar em materiais digitais.",
    href: "/qr-code",
    status: "available",
    category: "conversores",
    icon: QrCode,
    accent: "qr",
    seoTitle: "Gerador de QR Code online",
    seoDescription: "Crie QR Code online gratis para links e textos e baixe em PNG sem instalar programas.",
  },
  {
    slug: "txt-para-pdf",
    title: "TXT para PDF",
    shortTitle: "TXT para PDF",
    description: "Transforme arquivos TXT em PDF limpo e pronto para compartilhar.",
    longDescription: "Envie um arquivo TXT e gere um PDF organizado, com leitura confortavel, titulo opcional e download temporario.",
    href: "/txt-para-pdf",
    status: "available",
    category: "conversores",
    icon: FileText,
    accent: "pdf",
    seoTitle: "Converter TXT para PDF online",
    seoDescription: "Converta TXT para PDF online gratis, sem instalar programas e com download temporario.",
  },
  {
    slug: "markdown-para-pdf",
    title: "Markdown para PDF",
    shortTitle: "Markdown para PDF",
    description: "Converta arquivos Markdown em PDF para ler ou enviar.",
    longDescription: "Envie um arquivo MD ou Markdown e gere um PDF simples, preservando titulos, listas e texto principal.",
    href: "/markdown-para-pdf",
    status: "available",
    category: "conversores",
    icon: Code2,
    accent: "html",
    seoTitle: "Converter Markdown para PDF online",
    seoDescription: "Converta Markdown MD para PDF online com uma ferramenta simples e gratuita.",
  },
  {
    slug: "comprimir-imagem",
    title: "Comprimir imagem",
    shortTitle: "Comprimir imagem",
    description: "Reduza o tamanho de JPG, PNG ou WebP mantendo boa qualidade.",
    longDescription: "Envie uma imagem JPG, PNG ou WebP e baixe uma versao mais leve para sites, redes sociais, anexos e lojas virtuais.",
    href: "/comprimir-imagem",
    status: "available",
    category: "imagem",
    icon: FileImage,
    accent: "image",
    seoTitle: "Comprimir imagem online",
    seoDescription: "Comprima imagens JPG, PNG ou WebP online para reduzir o tamanho do arquivo.",
  },
  {
    slug: "redimensionar-imagem",
    title: "Redimensionar imagem",
    shortTitle: "Redimensionar",
    description: "Altere largura ou altura de imagens JPG, PNG e WebP.",
    longDescription: "Envie uma imagem, informe a largura ou altura desejada e baixe uma copia redimensionada sem perder proporcao.",
    href: "/redimensionar-imagem",
    status: "available",
    category: "imagem",
    icon: FileImage,
    accent: "image",
    seoTitle: "Redimensionar imagem online",
    seoDescription: "Redimensione imagens online por largura ou altura e baixe uma copia otimizada.",
  },
  {
    slug: "converter-imagem",
    title: "Converter JPG, PNG e WebP",
    shortTitle: "Converter imagem",
    description: "Converta imagens entre JPG, PNG e WebP.",
    longDescription: "Envie JPG, PNG ou WebP, escolha o formato final e baixe a imagem convertida em poucos segundos.",
    href: "/converter-imagem",
    status: "available",
    category: "imagem",
    icon: FileImage,
    accent: "image",
    seoTitle: "Converter imagem JPG PNG WebP online",
    seoDescription: "Converta imagens JPG, PNG e WebP online com download temporario.",
  },
  {
    slug: "video-para-mp3",
    title: "Vídeo para MP3",
    shortTitle: "Vídeo para MP3",
    description: "Extraia o áudio de vídeos e baixe em MP3.",
    longDescription: "Envie um video MP4, MOV, MKV, WEBM ou AVI e gere um arquivo MP3 leve para ouvir, guardar ou compartilhar.",
    href: "/video-para-mp3",
    status: "available",
    category: "audio",
    icon: Mic,
    accent: "audio",
    seoTitle: "Converter video para MP3 online",
    seoDescription: "Converta video para MP3 online extraindo o audio de MP4, MOV, MKV, WEBM e AVI.",
  },
  {
    slug: "html-para-pdf",
    title: "HTML para PDF",
    shortTitle: "HTML para PDF",
    description: "Converta paginas HTML em documentos PDF de forma rapida.",
    longDescription: "Envie um arquivo HTML, um ZIP com imagens e estilos, ou cole a URL de uma pagina publica para criar um PDF fiel ao conteudo original.",
    href: "/html-para-pdf",
    status: "available",
    category: "conversores",
    icon: Code2,
    accent: "html",
    seoTitle: "HTML para PDF online gratis",
    seoDescription: "Converta HTML, ZIP ou URL em PDF online com o Documentos Online - 4D Tech.",
  },
  {
    slug: "remover-fundo-de-imagem",
    title: "Remover fundo de imagem",
    shortTitle: "Remover fundo",
    description: "Remova o fundo de imagens PNG ou JPG de forma automatica.",
    longDescription: "Envie uma imagem PNG ou JPG e baixe o resultado em PNG com fundo transparente, pronto para lojas virtuais, apresentacoes e redes sociais.",
    href: "/remover-fundo-de-imagem",
    status: "available",
    category: "imagem",
    icon: FileImage,
    accent: "image",
    seoTitle: "Remover fundo de imagem online",
    seoDescription: "Remova fundo de imagem online e baixe PNG transparente em poucos cliques.",
  },
  {
    slug: "word-para-pdf",
    title: "Word para PDF",
    shortTitle: "Word para PDF",
    description: "Converta arquivos do Word em PDF com qualidade.",
    longDescription: "Converta seus documentos WORD para PDF com maxima qualidade, preservando o visual do arquivo DOC ou DOCX original.",
    href: "/word-para-pdf",
    status: "available",
    category: "conversores",
    icon: FileText,
    accent: "word",
    seoTitle: "Converter Word para PDF online",
    seoDescription: "Converta documentos DOC e DOCX em PDF online com privacidade e download temporario.",
  },
  {
    slug: "excel-para-pdf",
    title: "Excel para PDF",
    shortTitle: "Excel para PDF",
    description: "Converta planilhas do Excel para PDF.",
    longDescription: "Converta suas tabelas EXCEL para PDF com colunas ajustadas a largura da pagina. Escolha vertical ou horizontal.",
    href: "/excel-para-pdf",
    status: "available",
    category: "conversores",
    icon: Sheet,
    accent: "excel",
    seoTitle: "Converter Excel para PDF online",
    seoDescription: "Converta planilhas XLS e XLSX em PDF online, com orientacao vertical ou horizontal.",
  },
  {
    slug: "pdf-para-excel",
    title: "PDF para Excel",
    shortTitle: "PDF para Excel",
    description: "Extraia dados de PDFs para planilhas do Excel.",
    longDescription: "Converta dados em PDF para folhas de calculo EXCEL, facilitando a analise e organizacao das informacoes.",
    href: "/pdf-para-excel",
    status: "available",
    category: "pdf",
    icon: FileSpreadsheet,
    accent: "excel",
    seoTitle: "Converter PDF para Excel online",
    seoDescription: "Converta dados de PDF em planilha Excel XLSX online com download temporario.",
  },
  {
    slug: "pdf-para-word",
    title: "PDF para Word",
    shortTitle: "PDF para Word",
    description: "Converta PDFs em documentos Word editaveis.",
    longDescription: "Converta seus ficheiros PDF para documentos WORD com uma exatidao incrivel e edite o conteudo depois.",
    href: "/pdf-para-word",
    status: "available",
    category: "pdf",
    icon: FileType,
    accent: "word",
    seoTitle: "Converter PDF para Word online",
    seoDescription: "Converta PDF em Word DOCX online com download temporario e sem cadastro.",
  },
  {
    slug: "editar-pdf",
    title: "Editar PDF",
    shortTitle: "Editar PDF",
    description: "Edite PDF adicionando texto, formas e comentarios.",
    longDescription: "Edite PDF adicionando texto, formas, comentarios e destaques em uma ferramenta simples para o navegador.",
    href: "/editar-pdf",
    status: "available",
    category: "pdf",
    icon: Edit3,
    accent: "edit",
    seoTitle: "Editar PDF online",
    seoDescription: "Edite PDF online adicionando texto ou comentario e baixe o arquivo editado.",
  },
  {
    slug: "comprimir-pdf",
    title: "Comprimir PDF",
    shortTitle: "Comprimir PDF",
    description: "Reduza o tamanho de arquivos PDF para enviar ou compartilhar.",
    longDescription: "Envie um PDF e gere uma versao otimizada, mais leve para anexar em e-mails, sistemas e mensagens.",
    href: "/comprimir-pdf",
    status: "available",
    category: "pdf",
    icon: FileType,
    accent: "pdf",
    seoTitle: "Comprimir PDF online",
    seoDescription: "Comprima PDF online para reduzir o tamanho do arquivo sem instalar programas.",
  },
  {
    slug: "juntar-pdf",
    title: "Juntar PDF",
    shortTitle: "Juntar PDF",
    description: "Una dois ou mais PDFs em um unico arquivo.",
    longDescription: "Organize documentos, contratos e anexos juntando varios arquivos PDF em um so download temporario.",
    href: "/juntar-pdf",
    status: "available",
    category: "pdf",
    icon: FileType,
    accent: "pdf",
    seoTitle: "Juntar PDF online",
    seoDescription: "Junte varios arquivos PDF online em um unico documento de forma simples.",
  },
  {
    slug: "dividir-pdf",
    title: "Dividir PDF",
    shortTitle: "Dividir PDF",
    description: "Extraia paginas especificas de um PDF.",
    longDescription: "Escolha paginas ou intervalos para criar um novo PDF apenas com o conteudo que voce precisa.",
    href: "/dividir-pdf",
    status: "available",
    category: "pdf",
    icon: FileText,
    accent: "pdf",
    seoTitle: "Dividir PDF online",
    seoDescription: "Divida PDF online extraindo paginas ou intervalos especificos.",
  },
  {
    slug: "imagem-para-pdf",
    title: "Imagem para PDF",
    shortTitle: "Imagem para PDF",
    description: "Transforme imagens PNG ou JPG em PDF.",
    longDescription: "Envie fotos, comprovantes ou imagens e gere um PDF em paginas A4 prontas para imprimir ou compartilhar.",
    href: "/imagem-para-pdf",
    status: "available",
    category: "conversores",
    icon: FileImage,
    accent: "image",
    seoTitle: "Imagem para PDF online",
    seoDescription: "Converta imagens JPG ou PNG em PDF online com paginas organizadas.",
  },
  {
    slug: "pdf-para-jpg",
    title: "PDF para JPG",
    shortTitle: "PDF para JPG",
    description: "Converta paginas de PDF em imagens JPG.",
    longDescription: "Transforme cada pagina do PDF em imagem JPG e baixe tudo em um arquivo ZIP.",
    href: "/pdf-para-jpg",
    status: "available",
    category: "conversores",
    icon: FileImage,
    accent: "image",
    seoTitle: "Converter PDF para JPG online",
    seoDescription: "Converta PDF para imagens JPG online e baixe as paginas em ZIP.",
  },
  {
    slug: "assinar-pdf",
    title: "Assinar PDF",
    shortTitle: "Assinar PDF",
    description: "Adicione uma assinatura textual ao PDF.",
    longDescription: "Inclua uma assinatura, nome ou observacao em uma pagina do PDF com posicao e tamanho configuraveis.",
    href: "/assinar-pdf",
    status: "available",
    category: "pdf",
    icon: Edit3,
    accent: "edit",
    seoTitle: "Assinar PDF online",
    seoDescription: "Assine PDF online adicionando texto de assinatura em uma posicao escolhida.",
  },
  {
    slug: "proteger-pdf",
    title: "Proteger PDF",
    shortTitle: "Proteger PDF",
    description: "Adicione senha para proteger um PDF.",
    longDescription: "Crie uma copia protegida por senha para dificultar o acesso indevido ao conteudo do documento.",
    href: "/proteger-pdf",
    status: "available",
    category: "pdf",
    icon: FileText,
    accent: "pdf",
    seoTitle: "Proteger PDF com senha online",
    seoDescription: "Proteja PDF com senha online e baixe uma copia temporaria protegida.",
  },
  {
    slug: "remover-senha-pdf",
    title: "Remover senha de PDF",
    shortTitle: "Remover senha",
    description: "Remova a senha de um PDF quando voce souber a senha atual.",
    longDescription: "Envie um PDF protegido e informe a senha correta para gerar uma copia desbloqueada.",
    href: "/remover-senha-pdf",
    status: "available",
    category: "pdf",
    icon: FileText,
    accent: "pdf",
    seoTitle: "Remover senha de PDF online",
    seoDescription: "Remova senha de PDF online informando a senha atual do documento.",
  },
  {
    slug: "organizar-pdf",
    title: "Organizar PDF",
    shortTitle: "Organizar PDF",
    description: "Reordene ou selecione paginas do PDF.",
    longDescription: "Informe a nova ordem das paginas para gerar um PDF reorganizado com apenas as paginas desejadas.",
    href: "/organizar-pdf",
    status: "available",
    category: "pdf",
    icon: FileText,
    accent: "pdf",
    seoTitle: "Organizar PDF online",
    seoDescription: "Organize paginas de PDF online escolhendo a ordem ou removendo paginas.",
  },
];

export const availableTools = tools.filter((tool) => tool.status === "available");
export const getToolBySlug = (slug: string) => tools.find((tool) => tool.slug === slug);
