import type { LucideIcon } from "lucide-react";
import { Code2, Edit3, FileImage, FileSpreadsheet, FileText, FileType, Mic, QrCode, Sheet, Video } from "lucide-react";

export type ToolCategory = "pdf" | "imagem" | "conversores" | "audio";

export type ToolDefinition = {
  slug: string;
  title: string;
  shortTitle: string;
  description: string;
  longDescription: string;
  href: string;
  status: "available" | "soon";
  category: ToolCategory;
  icon: LucideIcon;
  accent: "html" | "image" | "word" | "excel" | "pdf" | "edit" | "audio" | "qr" | "video";
  seoTitle: string;
  seoDescription: string;
};

export const tools: ToolDefinition[] = [
  {
    slug: "baixar-video-youtube",
    title: "Baixar vídeo do YouTube",
    shortTitle: "YouTube para MP4",
    description: "Baixe vídeos autorizados do YouTube em MP4 até 1080p.",
    longDescription: "Cole um link de vídeo ou Short público do YouTube e gere um MP4 temporário na qualidade que preferir.",
    href: "/baixar-video-youtube",
    status: "available",
    category: "conversores",
    icon: Video,
    accent: "video",
    seoTitle: "Baixar vídeo do YouTube em MP4",
    seoDescription: "Baixe vídeos e Shorts autorizados do YouTube em MP4, com opções de até 1080p.",
  },
  {
    slug: "transcrever-audio-em-texto",
    title: "Transcrever áudio em texto",
    shortTitle: "Áudio para texto",
    description: "Transforme áudio ou vídeo curto em texto editável.",
    longDescription: "Envie MP3, WAV, M4A, OGG, WEBM ou MP4 e receba uma transcrição em TXT para copiar, revisar ou salvar.",
    href: "/transcrever-audio-em-texto",
    status: "available",
    category: "audio",
    icon: Mic,
    accent: "audio",
    seoTitle: "Transcrever áudio em texto online",
    seoDescription: "Transcreva áudio em texto online e baixe a transcrição em TXT sem instalar programas.",
  },
  {
    slug: "qr-code",
    title: "Gerador de QR Code",
    shortTitle: "QR Code",
    description: "Crie QR Code para links, textos, contatos e informações.",
    longDescription: "Digite um link ou texto e gere um QR Code em PNG, pronto para imprimir, compartilhar ou usar em materiais digitais.",
    href: "/qr-code",
    status: "available",
    category: "conversores",
    icon: QrCode,
    accent: "qr",
    seoTitle: "Gerador de QR Code online",
    seoDescription: "Crie QR Code online grátis para links e textos e baixe em PNG sem instalar programas.",
  },
  {
    slug: "txt-para-pdf",
    title: "TXT para PDF",
    shortTitle: "TXT para PDF",
    description: "Transforme arquivos TXT em PDF limpo e pronto para compartilhar.",
    longDescription: "Envie um arquivo TXT e gere um PDF organizado, com leitura confortável, título opcional e download temporário.",
    href: "/txt-para-pdf",
    status: "available",
    category: "conversores",
    icon: FileText,
    accent: "pdf",
    seoTitle: "Converter TXT para PDF online",
    seoDescription: "Converta TXT para PDF online grátis, sem instalar programas e com download temporário.",
  },
  {
    slug: "markdown-para-pdf",
    title: "Markdown para PDF",
    shortTitle: "Markdown para PDF",
    description: "Converta arquivos Markdown em PDF para ler ou enviar.",
    longDescription: "Envie um arquivo MD ou Markdown e gere um PDF simples, preservando títulos, listas e texto principal.",
    href: "/markdown-para-pdf",
    status: "available",
    category: "conversores",
    icon: Code2,
    accent: "html",
    seoTitle: "Converter Markdown para PDF online",
    seoDescription: "Converta Markdown MD para PDF online com uma ferramenta simples e gratuita.",
  },
  {
    slug: "comprimir-imagem",
    title: "Comprimir imagem",
    shortTitle: "Comprimir imagem",
    description: "Reduza o tamanho de JPG, PNG ou WebP mantendo boa qualidade.",
    longDescription: "Envie uma imagem JPG, PNG ou WebP e baixe uma versão mais leve para sites, redes sociais, anexos e lojas virtuais.",
    href: "/comprimir-imagem",
    status: "available",
    category: "imagem",
    icon: FileImage,
    accent: "image",
    seoTitle: "Comprimir imagem online",
    seoDescription: "Comprima imagens JPG, PNG ou WebP online para reduzir o tamanho do arquivo.",
  },
  {
    slug: "redimensionar-imagem",
    title: "Redimensionar imagem",
    shortTitle: "Redimensionar",
    description: "Altere largura ou altura de imagens JPG, PNG e WebP.",
    longDescription: "Envie uma imagem, informe a largura ou altura desejada e baixe uma cópia redimensionada sem perder proporção.",
    href: "/redimensionar-imagem",
    status: "available",
    category: "imagem",
    icon: FileImage,
    accent: "image",
    seoTitle: "Redimensionar imagem online",
    seoDescription: "Redimensione imagens online por largura ou altura e baixe uma cópia otimizada.",
  },
  {
    slug: "converter-imagem",
    title: "Converter JPG, PNG e WebP",
    shortTitle: "Converter imagem",
    description: "Converta imagens entre JPG, PNG e WebP.",
    longDescription: "Envie JPG, PNG ou WebP, escolha o formato final e baixe a imagem convertida em poucos segundos.",
    href: "/converter-imagem",
    status: "available",
    category: "imagem",
    icon: FileImage,
    accent: "image",
    seoTitle: "Converter imagem JPG PNG WebP online",
    seoDescription: "Converta imagens JPG, PNG e WebP online com download temporario.",
  },
  {
    slug: "video-para-mp3",
    title: "Vídeo para MP3",
    shortTitle: "Vídeo para MP3",
    description: "Extraia o áudio de vídeos e baixe em MP3.",
    longDescription: "Envie um vídeo MP4, MOV, MKV, WEBM ou AVI e gere um arquivo MP3 leve para ouvir, guardar ou compartilhar.",
    href: "/video-para-mp3",
    status: "available",
    category: "audio",
    icon: Mic,
    accent: "audio",
    seoTitle: "Converter vídeo para MP3 online",
    seoDescription: "Converta vídeo para MP3 online extraindo o áudio de MP4, MOV, MKV, WEBM e AVI.",
  },
  {
    slug: "html-para-pdf",
    title: "HTML para PDF",
    shortTitle: "HTML para PDF",
    description: "Converta páginas HTML em documentos PDF de forma rápida.",
    longDescription: "Envie um arquivo HTML, um ZIP com imagens e estilos, ou cole a URL de uma página pública para criar um PDF fiel ao conteúdo original.",
    href: "/html-para-pdf",
    status: "available",
    category: "conversores",
    icon: Code2,
    accent: "html",
    seoTitle: "HTML para PDF online grátis",
    seoDescription: "Converta HTML, ZIP ou URL em PDF online com o Documentos Online - 4D Tech.",
  },
  {
    slug: "remover-fundo-de-imagem",
    title: "Remover fundo de imagem",
    shortTitle: "Remover fundo",
    description: "Remova o fundo de imagens PNG ou JPG de forma automática.",
    longDescription: "Envie uma imagem PNG ou JPG e baixe o resultado em PNG com fundo transparente, pronto para lojas virtuais, apresentações e redes sociais.",
    href: "/remover-fundo-de-imagem",
    status: "available",
    category: "imagem",
    icon: FileImage,
    accent: "image",
    seoTitle: "Remover fundo de imagem online",
    seoDescription: "Remova fundo de imagem online e baixe PNG transparente em poucos cliques.",
  },
  {
    slug: "word-para-pdf",
    title: "Word para PDF",
    shortTitle: "Word para PDF",
    description: "Converta arquivos do Word em PDF com qualidade.",
    longDescription: "Converta seus documentos WORD para PDF com máxima qualidade, preservando o visual do arquivo DOC ou DOCX original.",
    href: "/word-para-pdf",
    status: "available",
    category: "conversores",
    icon: FileText,
    accent: "word",
    seoTitle: "Converter Word para PDF online",
    seoDescription: "Converta documentos DOC e DOCX em PDF online com privacidade e download temporário.",
  },
  {
    slug: "excel-para-pdf",
    title: "Excel para PDF",
    shortTitle: "Excel para PDF",
    description: "Converta planilhas do Excel para PDF.",
    longDescription: "Converta suas tabelas EXCEL para PDF com colunas ajustadas à largura da página. Escolha vertical ou horizontal.",
    href: "/excel-para-pdf",
    status: "available",
    category: "conversores",
    icon: Sheet,
    accent: "excel",
    seoTitle: "Converter Excel para PDF online",
    seoDescription: "Converta planilhas XLS e XLSX em PDF online, com orientação vertical ou horizontal.",
  },
  {
    slug: "pdf-para-excel",
    title: "PDF para Excel",
    shortTitle: "PDF para Excel",
    description: "Extraia dados de PDFs para planilhas do Excel.",
    longDescription: "Converta dados em PDF para folhas de cálculo EXCEL, facilitando a análise e organização das informações.",
    href: "/pdf-para-excel",
    status: "available",
    category: "pdf",
    icon: FileSpreadsheet,
    accent: "excel",
    seoTitle: "Converter PDF para Excel online",
    seoDescription: "Converta dados de PDF em planilha Excel XLSX online com download temporário.",
  },
  {
    slug: "pdf-para-word",
    title: "PDF para Word",
    shortTitle: "PDF para Word",
    description: "Converta PDFs em documentos Word editáveis.",
    longDescription: "Converta seus ficheiros PDF para documentos WORD com uma exatidão incrível e edite o conteúdo depois.",
    href: "/pdf-para-word",
    status: "available",
    category: "pdf",
    icon: FileType,
    accent: "word",
    seoTitle: "Converter PDF para Word online",
    seoDescription: "Converta PDF em Word DOCX online com download temporário e sem cadastro.",
  },
  {
    slug: "editar-pdf",
    title: "Editar PDF",
    shortTitle: "Editar PDF",
    description: "Edite PDF adicionando texto, formas e comentários.",
    longDescription: "Edite PDF adicionando texto, formas, comentários e destaques em uma ferramenta simples para o navegador.",
    href: "/editar-pdf",
    status: "available",
    category: "pdf",
    icon: Edit3,
    accent: "edit",
    seoTitle: "Editar PDF online",
    seoDescription: "Edite PDF online adicionando texto ou comentário e baixe o arquivo editado.",
  },
  {
    slug: "comprimir-pdf",
    title: "Comprimir PDF",
    shortTitle: "Comprimir PDF",
    description: "Reduza o tamanho de arquivos PDF para enviar ou compartilhar.",
    longDescription: "Envie um PDF e gere uma versão otimizada, mais leve para anexar em e-mails, sistemas e mensagens.",
    href: "/comprimir-pdf",
    status: "available",
    category: "pdf",
    icon: FileType,
    accent: "pdf",
    seoTitle: "Comprimir PDF online",
    seoDescription: "Comprima PDF online para reduzir o tamanho do arquivo sem instalar programas.",
  },
  {
    slug: "juntar-pdf",
    title: "Juntar PDF",
    shortTitle: "Juntar PDF",
    description: "Una dois ou mais PDFs em um único arquivo.",
    longDescription: "Organize documentos, contratos e anexos juntando vários arquivos PDF em um só download temporário.",
    href: "/juntar-pdf",
    status: "available",
    category: "pdf",
    icon: FileType,
    accent: "pdf",
    seoTitle: "Juntar PDF online",
    seoDescription: "Junte vários arquivos PDF online em um único documento de forma simples.",
  },
  {
    slug: "dividir-pdf",
    title: "Dividir PDF",
    shortTitle: "Dividir PDF",
    description: "Extraia páginas específicas de um PDF.",
    longDescription: "Escolha páginas ou intervalos para criar um novo PDF apenas com o conteúdo que você precisa.",
    href: "/dividir-pdf",
    status: "available",
    category: "pdf",
    icon: FileText,
    accent: "pdf",
    seoTitle: "Dividir PDF online",
    seoDescription: "Divida PDF online extraindo páginas ou intervalos específicos.",
  },
  {
    slug: "imagem-para-pdf",
    title: "Imagem para PDF",
    shortTitle: "Imagem para PDF",
    description: "Transforme imagens PNG ou JPG em PDF.",
    longDescription: "Envie fotos, comprovantes ou imagens e gere um PDF em páginas A4 prontas para imprimir ou compartilhar.",
    href: "/imagem-para-pdf",
    status: "available",
    category: "conversores",
    icon: FileImage,
    accent: "image",
    seoTitle: "Imagem para PDF online",
    seoDescription: "Converta imagens JPG ou PNG em PDF online com páginas organizadas.",
  },
  {
    slug: "pdf-para-jpg",
    title: "PDF para JPG",
    shortTitle: "PDF para JPG",
    description: "Converta páginas de PDF em imagens JPG.",
    longDescription: "Transforme cada página do PDF em imagem JPG e baixe tudo em um arquivo ZIP.",
    href: "/pdf-para-jpg",
    status: "available",
    category: "conversores",
    icon: FileImage,
    accent: "image",
    seoTitle: "Converter PDF para JPG online",
    seoDescription: "Converta PDF para imagens JPG online e baixe as páginas em ZIP.",
  },
  {
    slug: "assinar-pdf",
    title: "Assinar PDF",
    shortTitle: "Assinar PDF",
    description: "Adicione uma assinatura textual ao PDF.",
    longDescription: "Inclua uma assinatura, nome ou observação em uma página do PDF com posição e tamanho configuráveis.",
    href: "/assinar-pdf",
    status: "available",
    category: "pdf",
    icon: Edit3,
    accent: "edit",
    seoTitle: "Assinar PDF online",
    seoDescription: "Assine PDF online adicionando texto de assinatura em uma posição escolhida.",
  },
  {
    slug: "proteger-pdf",
    title: "Proteger PDF",
    shortTitle: "Proteger PDF",
    description: "Adicione senha para proteger um PDF.",
    longDescription: "Crie uma cópia protegida por senha para dificultar o acesso indevido ao conteúdo do documento.",
    href: "/proteger-pdf",
    status: "available",
    category: "pdf",
    icon: FileText,
    accent: "pdf",
    seoTitle: "Proteger PDF com senha online",
    seoDescription: "Proteja PDF com senha online e baixe uma cópia temporária protegida.",
  },
  {
    slug: "remover-senha-pdf",
    title: "Remover senha de PDF",
    shortTitle: "Remover senha",
    description: "Remova a senha de um PDF quando voce souber a senha atual.",
    longDescription: "Envie um PDF protegido e informe a senha correta para gerar uma cópia desbloqueada.",
    href: "/remover-senha-pdf",
    status: "available",
    category: "pdf",
    icon: FileText,
    accent: "pdf",
    seoTitle: "Remover senha de PDF online",
    seoDescription: "Remova senha de PDF online informando a senha atual do documento.",
  },
  {
    slug: "organizar-pdf",
    title: "Organizar PDF",
    shortTitle: "Organizar PDF",
    description: "Reordene ou selecione páginas do PDF.",
    longDescription: "Informe a nova ordem das páginas para gerar um PDF reorganizado com apenas as páginas desejadas.",
    href: "/organizar-pdf",
    status: "available",
    category: "pdf",
    icon: FileText,
    accent: "pdf",
    seoTitle: "Organizar PDF online",
    seoDescription: "Organize páginas de PDF online escolhendo a ordem ou removendo páginas.",
  },
];

export const availableTools = tools.filter((tool) => tool.status === "available");
export const getToolBySlug = (slug: string) => tools.find((tool) => tool.slug === slug);
